### ISSUE TITLE
Dynamo 2.0.3 | Ladybug 0.2.1 

### ISSUE THREAD

**Issue by RaquelMirraSantos** [ladybug-analysis-tools/ladybug-dynamo#43]
Hi,
I tried using the Ladybug 0.2.1 package for the first time in Revit 2020 with Dynamo 2.0.3, and the two nodes that I tried (Date Calculate HOY, and Import Location) were giving me the same error:

```
ERROR:
	invalid literal for float(): DynamoForRevit

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/ladybug-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 55, in <module>
  File "<string>", line 18, in tryGetPluginPath
ValueError: invalid literal for float(): DynamoForRevit
```

Could you provide me some guidance?

**Comment by ib990** [comment]
me too same problem here 
![image](https://user-images.githubusercontent.com/66656783/84183016-484c6980-aa59-11ea-81a7-c76126475225.png)
![image](https://user-images.githubusercontent.com/66656783/84183049-4edae100-aa59-11ea-95bf-0b92e0e3cffe.png)

**Comment by metobb** [comment]
Hi! 
I have the same issue.. I am using student version of Dynamo Revit.

Any solution for this case? 

![image](https://user-images.githubusercontent.com/59569553/89201432-c8063880-d5b1-11ea-8766-3493cabf970e.png)

**Comment by ptricktk** [comment]
Running Revit 2021 with latest updates. Still the same issue. I do not know what to do about this. We tried installing Ladybug-Core with pip to see if that solved the issue, but no luck.

Ladybug is running fine in Rhino/Grasshopper on the same machine.

**Comment by Babinoff** [comment]
It's all about "import and prepare py code" node in all ladybug nodes, what dont find package *.py files correctly anymore.
Made some sample node to fix it, put it in "ladybug-fixer" package.
![изображение](https://user-images.githubusercontent.com/36503488/94373745-0599c480-0110-11eb-823e-5ce961b456ad.png)
![изображение](https://user-images.githubusercontent.com/36503488/94373757-1b0eee80-0110-11eb-97bc-2a0823916856.png)
![изображение](https://user-images.githubusercontent.com/36503488/94373812-80fb7600-0110-11eb-8fb0-379f3dc0d65a.png)

**Comment by metobb** [comment]
@Babinoff Thanks for sharing it! I have tried your solution, however I am still getting Null out of ladybugfixer node. Could you tell me if I am missing something in my process? 

![image](https://user-images.githubusercontent.com/59569553/94423929-b7c1a280-0189-11eb-9f91-1a922452c02a.png)

**Comment by Babinoff** [comment]
I think it's all about the / signs in the file path, you used the \ sign, which needs to be escaped \\\ inside the python syntax, try to use / like in my screens.

**Comment by metobb** [comment]
I changed to "/" sign, but still getting Null out of it..  

![image](https://user-images.githubusercontent.com/59569553/94612538-876e2700-02a3-11eb-8591-0fa0a7e7f40e.png)

**Comment by metobb** [comment]
I downloaded the node from your package "ladybug-fixer", and it worked out :) thanks again!

**Comment by dh803** [comment]
@Babinoff Hey, Alex! Thanks for your solution. But in my case, it works for "import location", but not other nodes. I had no idea what's the problem. 
![15cdb3400ecf34187bd3522cf7c1956](https://user-images.githubusercontent.com/72803755/95863798-87b6f980-0d5c-11eb-8531-c4b76f587435.png)
![85138b7232aee8605214edf056f55da](https://user-images.githubusercontent.com/72803755/95863808-8ab1ea00-0d5c-11eb-9ddb-e52e77d4f88a.png)
![b32e3e3984b292aaf7e02c4533674ad](https://user-images.githubusercontent.com/72803755/95863819-8d144400-0d5c-11eb-8ae0-1aacb5fd15d3.png)

**Comment by Babinoff** [comment]
Did`nt test on all nodes, but sunpath works fine. 
Maybe better to take Simon version - https://github.com/sbreslav/ladybug-dynamo/tree/simon-fix
Arhiv of his files, to simply resave pacakge - https://1drv.ms/u/s!AvhRIUtKr8n2g9Mjq-HG8GEaWYsInA?e=pgAwYH
Like this - https://youtu.be/je50RoDQeoQ?t=250

**Comment by dh803** [comment]
Thank you Alex. I'll test again!

**Comment by dh803** [comment]
@Babinoff Hey Alex. Sorry to bother you again. Thanks to your help, the sun path is working now. But it shows this warning when I'm trying to use Legend Parameters :
![image](https://user-images.githubusercontent.com/72803755/97197897-1472a600-17a6-11eb-8516-06e46a4f3af9.png)

Any idea how to resolve it?

**Comment by adonis8233** [comment]
Hi, I'm new in Dynamo, does anyone could tell me where to find/write decompose outputs?

**Comment by Babinoff** [comment]
> 
> 
> @Babinoff Hey Alex. Sorry to bother you again. Thanks to your help, the sun path is working now. But it shows this warning when I'm trying to use Legend Parameters :
> ![image](https://user-images.githubusercontent.com/72803755/97197897-1472a600-17a6-11eb-8516-06e46a4f3af9.png)
> 
> Any idea how to resolve it?
I think he's waiting list of API Color and you give him DSCore.Color, which did Colore Range node.
https://www.revitapidocs.com/2019/3735f9b9-d477-09ea-25bd-67f34134595f.htm
